version: "3"
services:
  remix:
    image: node:18
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
    volumes:
      - .:/code
    working_dir: /code
    command: bash
  cypress:
    image: cypress/base:18.14.1
    environment:
      - HOST=0.0.0.0
    ports:
      - 3000:3000
      - 5555:5555
      - 8002:8002
    volumes:
      - .:/code
    working_dir: /code
    command: bash
